merge master into pact5 (#2037)
* pact version that support hashable-1.5

* update cabal.project.freeze

Change-Id: I53d40fc38a8b7cddeab3bb608ffc651dd8099ea4

* update pact pin

* update nix hackage index

Change-Id: I1f311862b5f2e66d659a17ac40b3d2844218b422

* Typos Update README.md (#2032)

"inquires"
Error: Incorrect word usage.
Correction: "inquiries"

"IMPORTANT NODE"
Error: Typo.
Correction: "IMPORTANT NOTE"

* Revert "revert rosetta test changes based on hashable update"

This reverts commit 9c1d9460d89703a3b3a041f13462f80c813ac004.

---------

Co-authored-by: chessai <chessai1996@gmail.com>
Co-authored-by: Dmitry <98899785+mdqst@users.noreply.github.com>